<body>
 <form class="formaction" action="formRechercheDate.php" method="GET">
                 <label for="client">Date début</label></br>
                 <input type="date" name="date_debut"></br>
                 
                <label for="client">Date fin</label></br>
                 <input type="date" name="date_fin"></br>
                   <input type="submit" name="submit" /> 
 
</form>
<?php  
            
            var_dump($resultdate);

?>

<?php foreach($resultdate as $date): ?>
            <article>
                <h3><?= htmlspecialchars($date['IDWEBdate']) ?>"</h3>
                <h3><?= htmlspecialchars($date['cat_title']) ?></h3>
                <h3><?= htmlspecialchars($date['date_debut']) ?></h3>
                 <h3><?= htmlspecialchars($date['date_fin']) ?></h3>
                <h3><?= htmlspecialchars($date['time_start']) ?></h3>
                <h3><?= htmlspecialchars($date['time_end']) ?></h3>
            </article>
            
            var_dump($resultdate);
        <?php endforeach; ?>

 <script type="text/javascript" src="js/rechercheDate.js"></script>
</body>